# Generated by Django 6.0.2 on 2026-02-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LattesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LattesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GRAD_DIPLOMA', 'Diploma de graduação'), ('POST_CERT', 'Certificado de pós-graduação'), ('COURSES', 'Cursos/minicursos complementares'), ('LANGUAGES', 'Cursos de idiomas'), ('EVENTS', 'Participação em eventos'), ('RESEARCH_EXT', 'Projetos de pesquisa/extensão'), ('RESEARCH_GROUP', 'Grupos de pesquisa'), ('PRESENTATIONS', 'Apresentações/palestras'), ('PUBLICATIONS', 'Publicações'), ('PROFESSIONAL', 'Atuação profissional'), ('AWARDS', 'Títulos/prêmios/menções'), ('COUNCIL_REG', 'Registro no conselho'), ('OTHER', 'Outros')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='lattes_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='siteapp.lattesrequest')),
            ],
        ),
    ]
